### ISSUE TITLE
ShortFormDirectoryEntry.getLength() should return getNameLength() + inodeSize

### ISSUE THREAD

**Issue by CoffeeForOven** [Nuix/jnode-fs#8]
https://github.com/Nuix/jnode-fs/blob/2ce2f8dd01c96cbe3b4f5c477b704c91e9ddd88e/src/main/java/org/jnode/fs/xfs/directory/ShortFormDirectoryEntry.java#L85

**Comment by JulioCesarParra** [comment]
Hi Erwin, I reviewed the code about the value 0x8 defined in the method getLength().  The name of the method is not correct,  its purpose in the code is to return the number of bytes required to find the next offset. The inodeSize represent a value different to read other data.  I will implement some changes to define a different method name and define a constant that represent the 8 bytes and plus the length of the name are used find and read the are required to find the next directory entry.

**Comment by CoffeeForOven** [comment]
Hi Julio. Let me take over this ticket to investigate and confirm.
